// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package incoterms.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Incoterms module
	public static java.util.List<incoterms.proxies.Incoterm> dS_Incoterms(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "Incoterms.DS_Incoterms", params);
			java.util.List<incoterms.proxies.Incoterm> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<incoterms.proxies.Incoterm>();
				for (IMendixObject obj : objs)
					result.add(incoterms.proxies.Incoterm.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}